#pragma once

namespace legacysdk::ui {
    enum class EUIScene {
        PartnernetPassword = 0,
        Intro = 1,
        SaveMessage = 2,
        MainMenu = 3,
        FullscreenProgress = 4,
        PauseMenu = 5,
        Crafting2x2Menu = 6,
        Crafting3x3Menu = 7,
        FurnaceMenu = 8,
        ContainerMenu = 9,
        LargeContainerMenu = 10,
        InventoryMenu = 11,
        DispenserMenu = 12,
        DebugOptions = 13,
        DebugTips = 14,
        HelpAndOptionsMenu = 15,
        HowToPlay = 16,
        HowToPlayMenu = 17,
        ControlsMenu = 18,
        SettingsOptionsMenu = 19,
        SettingsAudioMenu = 20,
        SettingsControlMenu = 21,
        SettingsGraphicsMenu = 22,
        SettingsUIMenu = 23,
        SettingsMenu = 24,
        LeaderboardsMenu = 25,
        Credits = 26,
        DeathMenu = 27,
        TutorialPopup = 28,
        CreateWorldMenu = 29,
        LoadOrJoinMenu = 30,
        JoinMenu = 31,
        SignEntryMenu = 32,
        InGameInfoMenu = 33,
        ConnectingProgress = 34,
        DLCOffersMenu = 35,
        SocialPost = 36,
        TrialExitUpsell = 37,
        LoadMenu = 38,
        Chat = 39,
        ReinstallMenu = 40,
        SkinSelectMenu = 41,
        TextEntry = 42,
        InGameHostOptionsMenu = 43,
        InGamePlayerOptionsMenu = 44,
        CreativeMenu = 45,
        LaunchMoreOptionsMenu = 46,
        DLCMainMenu = 47,
        NewUpdateMessage = 48,
        EnchantingMenu = 49,
        BrewingStandMenu = 50,
        EndPoem = 51,
        HUD = 52,
        TradingMenu = 53,
        AnvilMenu = 54,
        TeleportMenu = 55,
        Panorama = 56,
        Logo = 57,
        DebugUIConsole = 58,
        DebugUIMarketingGuide = 59,
        Tooltips = 60,
        PressStartToPlay = 61,
        MenuBackground = 62,
        Keyboard = 63,
        QuadrantSignin = 64,
        MessageBox = 65,
        Timer = 66,
        EULA = 67,
        InGameSaveManagementMenu = 68,
        DebugOverlay = 69,
        DebugItemEditor = 70,
        DebugCreateSchematic = 71,
        DebugSetCamera = 72,
        COUNT = 73
    };

    enum class EUINavigationAction {
        NavigateToHomeMenu,
        NavigateToScene,
        NavigateBack,
        CloseAllPlayersScenes,
        CloseUIScenes
    };

    enum class EUILayer {
        Debug = 0,
        Tooltips = 1,
        Error = 2,
        Alert = 3,
        Fullscreen = 4,
        Popup = 5,
        Scene = 6,
        HUD = 7,
        COUNT = 8
    };

    enum class EUIGroup {
        Fullscreen = 0,
        Player1 = 1,
        Player2 = 2,
        Player3 = 3,
        Player4 = 4,
        COUNT = 5,
        PAD = 6
    };
}
